CREATE DATABASE librarydb;
USE librarydb;

CREATE TABLE IF NOT EXISTS book (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(80) NOT NULL,
    AVAILABLE_COPIES TINYINT NOT NULL,
    TOTAL_COPIES TINYINT NOT NULL);
    
    
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
    SUBSCRIBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUBSCRIBER_NAME VARCHAR(80) NOT NULL,
    DATE_SUBSCRIBED DATE,
    DATE_RETURNED DATE,
    BOOK_ID INT,
    FOREIGN KEY (BOOK_ID)
        REFERENCES book (BOOK_ID)
        ON DELETE RESTRICT
);

insert into book(BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES)
values('The God of Small Things','Arundhati Roy',80,80);

